net: hns3: reduce stack usage in hclge_dbg_dump_tm_pri()
mainline inclusion
from mainline-v6.13-rc7
commit 2ff46b9eca2bb86c364942e86fd0145d56b62e40
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/ICMHOC
CVE: NA

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=2ff46b9eca2bb86c364942e86fd0145d56b62e40

----------------------------------------------------------------------

This function exceeds the stack frame warning limit:

drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c: In function 'hclge_dbg_dump_tm_pri':
drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c:1039:1: error: the frame size of 1408 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Use dynamic allocation for the largest stack object instead. It
would be nice to rewrite this file to completely avoid the extra
buffer and just use the one that was already allocated by debugfs,
but that is a much larger change.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20231204085735.4112882-1-arnd@kernel.org
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: Donghua Huang <huangdonghua3@h-partners.com>