sched_ext: Allow dequeue_task_scx to fail
mainline inclusion
from mainline-v6.12-rc1
commit 9ad2861b773d7da1cf3a5a04a4e8f1aa7d092bbb
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/IDC9YK

Reference: https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9ad2861b773d7da1cf3a5a04a4e8f1aa7d092bbb

--------------------------------

Since dequeue_task() allowed to fail, there is a compile error:

kernel/sched/ext.c:3630:19: error: initialization of ‘bool (*)(struct rq*, struct task_struct *, int)’ {aka ‘_Bool (*)(struct rq *, struct task_struct *, int)’} from incompatible pointer type ‘void (*)(struct rq*, struct task_struct *, int)’
  3630 |  .dequeue_task  = dequeue_task_scx,
       |                   ^~~~~~~~~~~~~~~~

Allow dequeue_task_scx to fail too.

Fixes: 863ccdbb918a ("sched: Allow sched_class::dequeue_task() to fail")
Signed-off-by: Yipeng Zou <zouyipeng@huawei.com>
Signed-off-by: Tejun Heo <tj@kernel.org>
Signed-off-by: Zicheng Qu <quzicheng@huawei.com>