scsi: mpi3mr: Reduce stack usage in mpi3mr_refresh_sas_ports()
mainline inclusion
from mainline-v6.12
commit 5cc2da0b60e5b4daf6cf7442ee66f1f91878c0b5
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ID37WW

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=5cc2da0b60e5b4daf6cf7442ee66f1f91878c0b5

--------------------------------
Actually this commit includes 2 upstream patches, another one is
scsi: mpi3mr: Increase maximum number of PHYs to 64 from 32, [ Upstream Commit ID cb5b60894602b12a63d3e08be88eaf26b2603c19 ], this patch
causes an issue of stack overflow,
Commit 5cc2da0b60e5b4daf6cf7442ee66f1f91878c0b5 fixes the stack usage issue,

SAS5116 controllers supports maximum 48 physical PHYs. Modify driver to
accommodate up to 64 PHYs (though current need is to support 48 PHYs).
Doubling the number of PHYs also doubled the stack usage of this function,
exceeding the 32-bit limit of 1024 bytes:

drivers/scsi/mpi3mr/mpi3mr_transport.c: In function 'mpi3mr_refresh_sas_ports':
drivers/scsi/mpi3mr/mpi3mr_transport.c:1818:1: error: the frame size of 1636 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Since the sas_io_unit_pg0 structure is already allocated dynamically, use
the same method here. The size of the allocation can be smaller based on
the actual number of phys now, so use this as an upper bound.

Signed-off-by: Sumit Saxena <sumit.saxena@broadcom.com>
Link: https://lore.kernel.org/r/20231123160132.4155-4-sumit.saxena@broadcom.com
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
Signed-off-by: Ranjan Kumar <ranjan.kumar@broadcom.com>
Signed-off-by: yk887999 <18618309255@163.com>