KVM: guest-memfd: fix unused-function warning
mainline inclusion
from mainline-v6.8-rc1
commit 80583d0cfd8ff44d60a5fa76a6bf3c08eb67c328
category: feature
bugzilla: https://atomgit.com/openeuler/kernel/issues/6819
CVE: N/A
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=80583d0cfd8ff44d60a5fa76a6bf3c08eb67c328

-------------------------------------

Hygon-SIG: commit 80583d0cfd8f upstream KVM: guest-memfd: fix
unused-function warning
Backport the guest-memory feature.

-------------------------------------

With migration disabled, one function becomes unused:

virt/kvm/guest_memfd.c:262:12: error: 'kvm_gmem_migrate_folio' defined but not used [-Werror=unused-function]
  262 | static int kvm_gmem_migrate_folio(struct address_space *mapping,
      |            ^~~~~~~~~~~~~~~~~~~~~~

Remove the #ifdef around the reference so that fallback_migrate_folio()
is never used.  The gmem implementation of the hook is trivial; since
the gmem mapping is unmovable, the pages should not be migrated anyway.

Fixes: a7800aa80ea4 ("KVM: Add KVM_CREATE_GUEST_MEMFD ioctl() for guest-specific backing memory")
Reported-by: Arnd Bergmann <arnd@arndb.de>
Suggested-by: Sean Christopherson <seanjc@google.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
[ Zhiquan Li: amend commit log. ]
Signed-off-by: Li Zhiquan <lizhiquan@hygon.cn>
Link: https://gitee.com/openeuler/kernel/pulls/18709
Reviewed-by: Wei Wang <wangwww@hygon.cn>