crypto: ccp - Have it depend on AMD_IOMMU
mainline inclusion
from mainline-v6.12
commit ee8ff8768735edc3e013837c4416f819543ddc17
category: Feature
bugzilla: https://gitee.com/openeuler/kernel/issues/ICQGHL
CVE: NA

Reference: https://github.com/torvalds/linux/commit/ee8ff8768735edc3e013837c4416f819543ddc17

--------------------------------

commit ee8ff8768735edc3e013837c4416f819543ddc17 upstream

sev-dev.c calls code in the AMD IOMMU now but that can't really work if
latter is not enabled in Kconfig:

  ld: vmlinux.o: in function `__sev_firmware_shutdown.isra.0':
  sev-dev.c:(.text+0x2501f0e): undefined reference to `amd_iommu_snp_disable'
  ld: vmlinux.o: in function `snp_rmptable_init':
  sev.c:(.init.text+0x26260): undefined reference to `amd_iommu_snp_en'
  make[2]: *** [scripts/Makefile.vmlinux:37: vmlinux] Error 1
  make: *** [Makefile:240: __sub-make] Error 2

Fix those deps.

Fixes: f366a8dac1b8 ("iommu/amd: Clean up RMP entries for IOMMU pages during SNP shutdown")
Signed-off-by: Borislav Petkov (AMD) <bp@alien8.de>
Link: https://lore.kernel.org/r/20240207204721.6189-1-bp@alien8.de
Signed-off-by: Jeevan deep J <j.jeevandeep@amd.com>