samples/bpf: fix compilation errors with cf-protection option
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IAQBOF

--------------------------------

Currently, compiling the bpf programs will result the compilation errors
with the cf-protection option as follows in arm64 and loongarch64 machine
when using gcc 12.3.1 and clang 17.0.6. This commit fixes the compilation
errors by limited the cf-protection option only used in x86 platform.

[root@localhost linux]# make M=samples/bpf
	......
  CLANG-bpf  samples/bpf/xdp2skb_meta_kern.o
error: option 'cf-protection=return' cannot be specified on this target
error: option 'cf-protection=branch' cannot be specified on this target
2 errors generated.
  CLANG-bpf  samples/bpf/syscall_tp_kern.o
error: option 'cf-protection=return' cannot be specified on this target
error: option 'cf-protection=branch' cannot be specified on this target
2 errors generated.
	......

Link: https://lore.kernel.org/bpf/20240815135524.140675-1-13667453960@163.com
Fixes: 34f6e38f58db ("samples/bpf: fix warning with ignored-attributes")
Reported-by: Jiangshan Yi <yijiangshan@kylinos.cn>
Tested-by: Qiang Wang <wangqiang1@kylinos.cn>
Signed-off-by: Jiangshan Yi <yijiangshan@kylinos.cn>