LoongArch, unistd: add missing __NR_getrlimit system call number
kylin inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/IB32YT

--------------------------------

The compilation error of qtwebengine is as follows:

third_party/lss/linux_syscall_support.h: In function 'int sys_getrlimit(int, kernel_rlimit*)':
third_party/lss/linux_syscall_support.h:2843:39: error: '__NR_getrlimit' was not declared in this scope
      : "i"(__NR_##name) , ## args

Signed-off-by: Li ZhiGang <lizhigang@kylinos.cn>