iommu/amd: Fix compile error for unused function
mainline inclusion
from mainline-v6.5-rc1
commit 1ce018df87640adb139c8418785ad3b6e4376bd3
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/IBTVRA

----------------------------------------

commit 1ce018df87640adb139c8418785ad3b6e4376bd3 upstream

Recent changes introduced a compile error:

drivers/iommu/amd/iommu.c:1285:13: error: ‘iommu_flush_irt_and_complete’ defined but not used [-Werror=unused-function]
 1285 | static void iommu_flush_irt_and_complete(struct amd_iommu *iommu, u16 devid)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

This happens with defconfig-x86_64 because AMD IOMMU is enabled but
CONFIG_IRQ_REMAP is disabled. Move the function under #ifdef
CONFIG_IRQ_REMAP to fix the error.

Signed-off-by: Joerg Roedel <jroedel@suse.de>
Signed-off-by: Jeevan deep J <j.jeevandeep@amd.com>
Signed-off-by: mohanasv <mohanasv@amd.com>