interference: Fix compilation issue
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ICAOAT

--------------------------------

kernel test robot reported the following compilation error:

drivers/base/arch_topology.c:811:2: error: implicit declaration of
function 'cgroup_ifs_set_smt' [-Werror=implicit-function-declaration]

Let's fix it by adding cgroup_ifs_set_smt related header file.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202505282112.qVJOB1Zd-lkp@intel.com/
Fixes: edff31302c6d ("interference: Add smt interference track support")
Signed-off-by: Pu Lehui <pulehui@huawei.com>