ath9k: htc: clean up statistics macros
stable inclusion
from stable-v4.19.276
commit 323b7a98f26ff041cbe7458bba010375a8eb828f
category: bugfix
bugzilla: https://gitee.com/openeuler/kernel/issues/ICY4GK
CVE: CVE-2023-53199

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=323b7a98f26ff041cbe7458bba010375a8eb828f

--------------------------------

[ Upstream commit d7fc76039b74ad37b7056d5607b05d7cb31a5404 ]

I've changed *STAT_* macros a bit in previous patch and I seems like
they become really unreadable. Align these macros definitions to make
code cleaner and fix folllowing checkpatch warning

ERROR: Macros with complex values should be enclosed in parentheses

Also, statistics macros now accept an hif_dev as argument, since
macros that depend on having a local variable with a magic name
don't abide by the coding style.

No functional change

Suggested-by: Jeff Johnson <quic_jjohnson@quicinc.com>
Signed-off-by: Pavel Skripkin <paskripkin@gmail.com>
Acked-by: Toke Høiland-Jørgensen <toke@toke.dk>
Signed-off-by: Kalle Valo <quic_kvalo@quicinc.com>
Link: https://lore.kernel.org/r/ebb2306d06a496cd1b032155ae52fdc5fa8cc2c5.1655145743.git.paskripkin@gmail.com
Stable-dep-of: 0af54343a762 ("wifi: ath9k: hif_usb: clean up skbs if ath9k_hif_usb_rx_stream() fails")
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Ziming Du <duziming2@huawei.com>