net: hns3: reduce stack usage in hclge_dbg_dump_tm_pri()
mainline inclusion
from mainline-private-6.6
commit e94eda67b7b401cfab682f14477c69185ce1920d
category: feature
bugzilla: https://gitee.com/openeuler/kernel/issues/ICHMW9
CVE: NA

Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e94eda67b7b401cfab682f14477c69185ce1920d

----------------------------------------------------------------------

This function exceeds the stack frame warning limit:

drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c: In function 'hclge_dbg_dump_tm_pri':
drivers/net/ethernet/hisilicon/hns3/hns3pf/hclge_debugfs.c:1039:1: error: the frame size of 1408 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

Use dynamic allocation for the largest stack object instead. It
would be nice to rewrite this file to completely avoid the extra
buffer and just use the one that was already allocated by debugfs,
but that is a much larger change.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20231204085735.4112882-1-arnd@kernel.org
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: huangdonghua <huangdonghua3@h-partners.com>