arm64: entry: Fix ACTLR_XCALL_XINT not set build problem
hulk inclusion
category: bugfix
bugzilla: https://gitee.com/openeuler/release-management/issues/IBV2E4

--------------------------------

When ACTLR_XCALL_XINT not set, the "el0t_64_xcall" and "el0t_64_xint"
will not be defind, the following build problem occurs.

Define el0t_64_xcall and el0t_64_xint unconditionally to fix it
because the vectors_xcall_xint will be used in alternative_if/else
code and must be defined unconditionally.

	aarch64-linux-gnu-ld: arch/arm64/kernel/entry.o: in function `vectors_xcall_xint':
	./arch/arm64/kernel/entry.S:596: undefined reference to `el0t_64_xcall'
	aarch64-linux-gnu-ld: ./arch/arm64/kernel/entry.S:596: undefined reference to `el0t_64_xcall'
	aarch64-linux-gnu-ld: ./arch/arm64/kernel/entry.S:597: undefined reference to `el0t_64_xint'

Fixes: 7f2e02718bba ("arm64: entry: Support hardware xcall and xint")
Signed-off-by: Jinjie Ruan <ruanjinjie@huawei.com>