perf maps: Use a pointer for kmaps
struct maps is reference counted, using a pointer is more idiomatic.

Committer notes:

Delay:

maps = machine__kernel_maps(&vmlinux);

To after:

  machine__init(&vmlinux, "", HOST_KERNEL_ID);

To avoid this on f34:

In file included from /var/home/acme/git/perf/tools/perf/util/bu
ild-id.h:10,
  from /var/home/acme/git/perf/tools/perf/util/dso.h:13,
  from tests/vmlinux-kallsyms.c:8:
In function ‘machine__kernel_maps’,
  inlined from ‘test__vmlinux_matches_kallsyms’ at tests/vmlin
    ux-kallsyms.c:122:22:
/var/home/acme/git/perf/tools/perf/util/machine.h:86:23: error:
  ‘vmlinux.kmaps’ is used uninitialized [-Werror=uninitialized]
  86 |return machine->kmaps;
     |~~~~~~~^~~~~~~
  tests/vmlinux-kallsyms.c: In function ‘test__vmlinux_matches_k
    allsyms’:
  tests/vmlinux-kallsyms.c:121:34: note: ‘vmlinux’ declared here
  121 |struct machine kallsyms, vmlinux;
      |^~~~~~~
  cc1: all warnings being treated as errors

Signed-off-by: Ian Rogers <irogers@google.com>

Merge this patch used to solve the probleam that coredump occurs in
the perf tool in stable-5.10.

Reproduction method of coredump:
1.perf record -b sleep 10
2.perf report

Reference:https://github.com/torvalds/linux/commit/1a97cee604dcbdba6c75984b7227223d599ddf32
Conflict:Modified machine.c context due to e8719468ae39 not merge.

Signed-off-by: langfei <langfei@huawei.com>